version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    image: node:12
    volumes:
      - .:/app
    ports:
      - 3001:3000
    environment:
      - PATH=/app/api/node_modules/.bin:$PATH
    depends_on:
      - prisma
      - postgres
    working_dir: /app/api
    command:
      - /bin/sh
      - -c
      - |
        yarn
        sleep 10
        graphql get-schema --project database
        graphql codegen --project database
        yarn start:dev

  frontend:
    image: node:12-alpine
    depends_on:
      - prisma
      - postgres
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - .:/app
    working_dir: /app/frontend
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        cd /frontend
        yarn
        yarn start

  prisma-generate:
    image: node:12-alpine
    depends_on:
      - prisma
      - postgres
    volumes:
      - .:/app
    working_dir: /app/database
    environment:
      - PATH=/app/database/node_modules/.bin:$PATH
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        yarn
        prisma deploy
        prisma generate

volumes:
  postgres:
